// ============================================================
//  BASE DE DONNÉES DES INGRÉDIENTS (kcal / 100g)
// ============================================================

const INGREDIENTS_DB = [

  // ── CÉRÉALES & FÉCULENTS ─────────────────────────────────
  { id: "ing_001", name: "Riz blanc cuit", kcal: 130, category: "Céréales & Féculents" },
  { id: "ing_002", name: "Riz blanc cru", kcal: 358, category: "Céréales & Féculents" },
  { id: "ing_003", name: "Riz brun cuit", kcal: 112, category: "Céréales & Féculents" },
  { id: "ing_004", name: "Riz brun cru", kcal: 340, category: "Céréales & Féculents" },
  { id: "ing_005", name: "Riz basmati cuit", kcal: 121, category: "Céréales & Féculents" },
  { id: "ing_006", name: "Riz jasmin cuit", kcal: 129, category: "Céréales & Féculents" },
  { id: "ing_007", name: "Riz sauvage cuit", kcal: 101, category: "Céréales & Féculents" },
  { id: "ing_008", name: "Pâtes cuites", kcal: 131, category: "Céréales & Féculents" },
  { id: "ing_009", name: "Pâtes sèches", kcal: 352, category: "Céréales & Féculents" },
  { id: "ing_010", name: "Pâtes complètes cuites", kcal: 124, category: "Céréales & Féculents" },
  { id: "ing_011", name: "Pâtes complètes sèches", kcal: 330, category: "Céréales & Féculents" },
  { id: "ing_012", name: "Spaghetti cuits", kcal: 131, category: "Céréales & Féculents" },
  { id: "ing_013", name: "Tagliatelles cuites", kcal: 135, category: "Céréales & Féculents" },
  { id: "ing_014", name: "Penne cuites", kcal: 131, category: "Céréales & Féculents" },
  { id: "ing_015", name: "Fusilli cuits", kcal: 131, category: "Céréales & Féculents" },
  { id: "ing_016", name: "Gnocchis cuits", kcal: 130, category: "Céréales & Féculents" },
  { id: "ing_017", name: "Pain blanc", kcal: 265, category: "Céréales & Féculents" },
  { id: "ing_018", name: "Pain complet", kcal: 247, category: "Céréales & Féculents" },
  { id: "ing_019", name: "Pain de seigle", kcal: 259, category: "Céréales & Féculents" },
  { id: "ing_020", name: "Pain aux céréales", kcal: 243, category: "Céréales & Féculents" },
  { id: "ing_021", name: "Baguette", kcal: 272, category: "Céréales & Féculents" },
  { id: "ing_022", name: "Brioche", kcal: 385, category: "Céréales & Féculents" },
  { id: "ing_023", name: "Pain de mie blanc", kcal: 266, category: "Céréales & Féculents" },
  { id: "ing_024", name: "Pain pita", kcal: 275, category: "Céréales & Féculents" },
  { id: "ing_025", name: "Tortilla de blé", kcal: 306, category: "Céréales & Féculents" },
  { id: "ing_026", name: "Tortilla de maïs", kcal: 218, category: "Céréales & Féculents" },
  { id: "ing_027", name: "Flocons d'avoine", kcal: 370, category: "Céréales & Féculents" },
  { id: "ing_028", name: "Quinoa cuit", kcal: 120, category: "Céréales & Féculents" },
  { id: "ing_029", name: "Quinoa cru", kcal: 368, category: "Céréales & Féculents" },
  { id: "ing_030", name: "Pomme de terre cuite", kcal: 87, category: "Céréales & Féculents" },
  { id: "ing_031", name: "Pomme de terre crue", kcal: 77, category: "Céréales & Féculents" },
  { id: "ing_032", name: "Pomme de terre vapeur", kcal: 82, category: "Céréales & Féculents" },
  { id: "ing_033", name: "Frites maison", kcal: 274, category: "Céréales & Féculents" },
  { id: "ing_034", name: "Frites surgelées cuites", kcal: 270, category: "Céréales & Féculents" },
  { id: "ing_035", name: "Patate douce cuite", kcal: 90, category: "Céréales & Féculents" },
  { id: "ing_036", name: "Patate douce crue", kcal: 86, category: "Céréales & Féculents" },
  { id: "ing_037", name: "Farine de blé T45", kcal: 364, category: "Céréales & Féculents" },
  { id: "ing_038", name: "Farine de blé T80", kcal: 348, category: "Céréales & Féculents" },
  { id: "ing_039", name: "Farine de maïs", kcal: 362, category: "Céréales & Féculents" },
  { id: "ing_040", name: "Farine de riz", kcal: 366, category: "Céréales & Féculents" },
  { id: "ing_041", name: "Semoule cuite", kcal: 112, category: "Céréales & Féculents" },
  { id: "ing_042", name: "Semoule sèche", kcal: 357, category: "Céréales & Féculents" },
  { id: "ing_043", name: "Polenta cuite", kcal: 70, category: "Céréales & Féculents" },
  { id: "ing_044", name: "Boulgour cuit", kcal: 83, category: "Céréales & Féculents" },
  { id: "ing_045", name: "Boulgour cru", kcal: 342, category: "Céréales & Féculents" },
  { id: "ing_046", name: "Millet cuit", kcal: 119, category: "Céréales & Féculents" },
  { id: "ing_047", name: "Sarrasin cuit", kcal: 92, category: "Céréales & Féculents" },
  { id: "ing_048", name: "Maïs en boîte", kcal: 86, category: "Céréales & Féculents" },
  { id: "ing_049", name: "Maïs cru", kcal: 96, category: "Céréales & Féculents" },
  { id: "ing_050", name: "Chapelure", kcal: 395, category: "Céréales & Féculents" },
  { id: "ing_051", name: "Crackers", kcal: 422, category: "Céréales & Féculents" },
  { id: "ing_052", name: "Biscottes", kcal: 390, category: "Céréales & Féculents" },

  // ── VIANDES ──────────────────────────────────────────────
  { id: "ing_101", name: "Poulet blanc cuit", kcal: 165, category: "Viandes" },
  { id: "ing_102", name: "Poulet blanc cru", kcal: 110, category: "Viandes" },
  { id: "ing_103", name: "Poulet cuisse cuite", kcal: 184, category: "Viandes" },
  { id: "ing_104", name: "Poulet cuisse crue", kcal: 150, category: "Viandes" },
  { id: "ing_105", name: "Poulet aile cuite", kcal: 203, category: "Viandes" },
  { id: "ing_106", name: "Poulet entier rôti", kcal: 190, category: "Viandes" },
  { id: "ing_107", name: "Dinde blanc cuit", kcal: 135, category: "Viandes" },
  { id: "ing_108", name: "Dinde blanc cru", kcal: 104, category: "Viandes" },
  { id: "ing_109", name: "Canard cuit", kcal: 337, category: "Viandes" },
  { id: "ing_110", name: "Bœuf haché 5% cuit", kcal: 137, category: "Viandes" },
  { id: "ing_111", name: "Bœuf haché 5% cru", kcal: 121, category: "Viandes" },
  { id: "ing_112", name: "Bœuf haché 15% cuit", kcal: 215, category: "Viandes" },
  { id: "ing_113", name: "Bœuf haché 15% cru", kcal: 196, category: "Viandes" },
  { id: "ing_114", name: "Bœuf haché 20% cru", kcal: 254, category: "Viandes" },
  { id: "ing_115", name: "Steak de bœuf cuit", kcal: 207, category: "Viandes" },
  { id: "ing_116", name: "Steak de bœuf cru", kcal: 176, category: "Viandes" },
  { id: "ing_117", name: "Bœuf bourguignon cuit", kcal: 180, category: "Viandes" },
  { id: "ing_118", name: "Entrecôte cuite", kcal: 263, category: "Viandes" },
  { id: "ing_119", name: "Filet de bœuf cuit", kcal: 193, category: "Viandes" },
  { id: "ing_120", name: "Veau escalope cuite", kcal: 175, category: "Viandes" },
  { id: "ing_121", name: "Veau escalope crue", kcal: 109, category: "Viandes" },
  { id: "ing_122", name: "Porc filet cuit", kcal: 143, category: "Viandes" },
  { id: "ing_123", name: "Porc filet cru", kcal: 121, category: "Viandes" },
  { id: "ing_124", name: "Côte de porc cuite", kcal: 231, category: "Viandes" },
  { id: "ing_125", name: "Lardons fumés", kcal: 337, category: "Viandes" },
  { id: "ing_126", name: "Lardons allumettes crus", kcal: 316, category: "Viandes" },
  { id: "ing_127", name: "Bacon cuit", kcal: 541, category: "Viandes" },
  { id: "ing_128", name: "Jambon blanc", kcal: 107, category: "Viandes" },
  { id: "ing_129", name: "Jambon cru / serrano", kcal: 268, category: "Viandes" },
  { id: "ing_130", name: "Jambon de Bayonne", kcal: 243, category: "Viandes" },
  { id: "ing_131", name: "Chorizo", kcal: 455, category: "Viandes" },
  { id: "ing_132", name: "Saucisse de Francfort", kcal: 274, category: "Viandes" },
  { id: "ing_133", name: "Saucisse de Toulouse crue", kcal: 310, category: "Viandes" },
  { id: "ing_134", name: "Merguez crue", kcal: 290, category: "Viandes" },
  { id: "ing_135", name: "Chipolata crue", kcal: 300, category: "Viandes" },
  { id: "ing_136", name: "Saucisson sec", kcal: 430, category: "Viandes" },
  { id: "ing_137", name: "Mortadelle", kcal: 311, category: "Viandes" },
  { id: "ing_138", name: "Agneau côtelette cuite", kcal: 294, category: "Viandes" },
  { id: "ing_139", name: "Agneau gigot cuit", kcal: 191, category: "Viandes" },
  { id: "ing_140", name: "Agneau haché cru", kcal: 200, category: "Viandes" },

  // ── POISSONS & FRUITS DE MER ─────────────────────────────
  { id: "ing_201", name: "Saumon cuit", kcal: 208, category: "Poissons & Fruits de mer" },
  { id: "ing_202", name: "Saumon cru", kcal: 182, category: "Poissons & Fruits de mer" },
  { id: "ing_203", name: "Saumon fumé", kcal: 170, category: "Poissons & Fruits de mer" },
  { id: "ing_204", name: "Thon en boîte (eau)", kcal: 116, category: "Poissons & Fruits de mer" },
  { id: "ing_205", name: "Thon en boîte (huile)", kcal: 198, category: "Poissons & Fruits de mer" },
  { id: "ing_206", name: "Thon frais cru", kcal: 144, category: "Poissons & Fruits de mer" },
  { id: "ing_207", name: "Cabillaud cuit", kcal: 105, category: "Poissons & Fruits de mer" },
  { id: "ing_208", name: "Cabillaud cru", kcal: 82, category: "Poissons & Fruits de mer" },
  { id: "ing_209", name: "Sole cuite", kcal: 91, category: "Poissons & Fruits de mer" },
  { id: "ing_210", name: "Lieu noir cuit", kcal: 90, category: "Poissons & Fruits de mer" },
  { id: "ing_211", name: "Lieu jaune cuit", kcal: 96, category: "Poissons & Fruits de mer" },
  { id: "ing_212", name: "Dorade cuite", kcal: 131, category: "Poissons & Fruits de mer" },
  { id: "ing_213", name: "Dorade crue", kcal: 96, category: "Poissons & Fruits de mer" },
  { id: "ing_214", name: "Bar / Loup cuit", kcal: 124, category: "Poissons & Fruits de mer" },
  { id: "ing_215", name: "Truite cuite", kcal: 149, category: "Poissons & Fruits de mer" },
  { id: "ing_216", name: "Maquereau cuit", kcal: 262, category: "Poissons & Fruits de mer" },
  { id: "ing_217", name: "Maquereau cru", kcal: 205, category: "Poissons & Fruits de mer" },
  { id: "ing_218", name: "Sardine en boîte", kcal: 208, category: "Poissons & Fruits de mer" },
  { id: "ing_219", name: "Sardine fraîche crue", kcal: 135, category: "Poissons & Fruits de mer" },
  { id: "ing_220", name: "Hareng fumé", kcal: 228, category: "Poissons & Fruits de mer" },
  { id: "ing_221", name: "Anchois en boîte", kcal: 210, category: "Poissons & Fruits de mer" },
  { id: "ing_222", name: "Tilapia cuit", kcal: 128, category: "Poissons & Fruits de mer" },
  { id: "ing_223", name: "Crevettes cuites", kcal: 99, category: "Poissons & Fruits de mer" },
  { id: "ing_224", name: "Crevettes crues", kcal: 85, category: "Poissons & Fruits de mer" },
  { id: "ing_225", name: "Gambas cuites", kcal: 105, category: "Poissons & Fruits de mer" },
  { id: "ing_226", name: "Moules cuites", kcal: 86, category: "Poissons & Fruits de mer" },
  { id: "ing_227", name: "Palourdes cuites", kcal: 148, category: "Poissons & Fruits de mer" },
  { id: "ing_228", name: "Calamars crus", kcal: 92, category: "Poissons & Fruits de mer" },
  { id: "ing_229", name: "Calamars frits", kcal: 175, category: "Poissons & Fruits de mer" },
  { id: "ing_230", name: "Poulpe cuit", kcal: 82, category: "Poissons & Fruits de mer" },
  { id: "ing_231", name: "Homard cuit", kcal: 89, category: "Poissons & Fruits de mer" },
  { id: "ing_232", name: "Crabe en boîte", kcal: 97, category: "Poissons & Fruits de mer" },
  { id: "ing_233", name: "Surimi", kcal: 99, category: "Poissons & Fruits de mer" },
  { id: "ing_234", name: "Poisson pané surgelé", kcal: 218, category: "Poissons & Fruits de mer" },

  // ── ŒUFS ─────────────────────────────────────────────────
  { id: "ing_301", name: "Œuf entier cru", kcal: 155, category: "Œufs" },
  { id: "ing_302", name: "Œuf dur", kcal: 155, category: "Œufs" },
  { id: "ing_303", name: "Œuf au plat", kcal: 196, category: "Œufs" },
  { id: "ing_304", name: "Œuf brouillé", kcal: 149, category: "Œufs" },
  { id: "ing_305", name: "Œuf poché", kcal: 143, category: "Œufs" },
  { id: "ing_306", name: "Blanc d'œuf", kcal: 52, category: "Œufs" },
  { id: "ing_307", name: "Jaune d'œuf", kcal: 322, category: "Œufs" },

  // ── LÉGUMES ──────────────────────────────────────────────
  { id: "ing_401", name: "Tomate crue", kcal: 18, category: "Légumes" },
  { id: "ing_402", name: "Tomate cuite", kcal: 24, category: "Légumes" },
  { id: "ing_403", name: "Tomates cerises", kcal: 18, category: "Légumes" },
  { id: "ing_404", name: "Tomates séchées", kcal: 258, category: "Légumes" },
  { id: "ing_405", name: "Concombre cru", kcal: 15, category: "Légumes" },
  { id: "ing_406", name: "Salade verte (laitue)", kcal: 15, category: "Légumes" },
  { id: "ing_407", name: "Roquette", kcal: 25, category: "Légumes" },
  { id: "ing_408", name: "Mâche", kcal: 21, category: "Légumes" },
  { id: "ing_409", name: "Épinards crus", kcal: 23, category: "Légumes" },
  { id: "ing_410", name: "Épinards cuits", kcal: 29, category: "Légumes" },
  { id: "ing_411", name: "Épinards surgelés", kcal: 21, category: "Légumes" },
  { id: "ing_412", name: "Brocoli cru", kcal: 34, category: "Légumes" },
  { id: "ing_413", name: "Brocoli cuit", kcal: 35, category: "Légumes" },
  { id: "ing_414", name: "Chou-fleur cru", kcal: 25, category: "Légumes" },
  { id: "ing_415", name: "Chou-fleur cuit", kcal: 23, category: "Légumes" },
  { id: "ing_416", name: "Chou blanc cru", kcal: 25, category: "Légumes" },
  { id: "ing_417", name: "Chou rouge cru", kcal: 31, category: "Légumes" },
  { id: "ing_418", name: "Chou vert cuit", kcal: 28, category: "Légumes" },
  { id: "ing_419", name: "Chou de Bruxelles cuits", kcal: 43, category: "Légumes" },
  { id: "ing_420", name: "Choux de Bruxelles crus", kcal: 43, category: "Légumes" },
  { id: "ing_421", name: "Carottes crues", kcal: 41, category: "Légumes" },
  { id: "ing_422", name: "Carottes cuites", kcal: 35, category: "Légumes" },
  { id: "ing_423", name: "Carottes râpées", kcal: 41, category: "Légumes" },
  { id: "ing_424", name: "Courgette crue", kcal: 17, category: "Légumes" },
  { id: "ing_425", name: "Courgette cuite", kcal: 17, category: "Légumes" },
  { id: "ing_426", name: "Poivron rouge cru", kcal: 31, category: "Légumes" },
  { id: "ing_427", name: "Poivron vert cru", kcal: 20, category: "Légumes" },
  { id: "ing_428", name: "Poivron jaune cru", kcal: 27, category: "Légumes" },
  { id: "ing_429", name: "Poivron cuit", kcal: 29, category: "Légumes" },
  { id: "ing_430", name: "Oignon cru", kcal: 40, category: "Légumes" },
  { id: "ing_431", name: "Oignon cuit", kcal: 44, category: "Légumes" },
  { id: "ing_432", name: "Oignon rouge cru", kcal: 40, category: "Légumes" },
  { id: "ing_433", name: "Échalote", kcal: 72, category: "Légumes" },
  { id: "ing_434", name: "Ciboulette", kcal: 30, category: "Légumes" },
  { id: "ing_435", name: "Poireau cru", kcal: 31, category: "Légumes" },
  { id: "ing_436", name: "Poireau cuit", kcal: 31, category: "Légumes" },
  { id: "ing_437", name: "Ail cru", kcal: 149, category: "Légumes" },
  { id: "ing_438", name: "Ail en poudre", kcal: 331, category: "Légumes" },
  { id: "ing_439", name: "Champignons de Paris crus", kcal: 22, category: "Légumes" },
  { id: "ing_440", name: "Champignons de Paris cuits", kcal: 26, category: "Légumes" },
  { id: "ing_441", name: "Champignons shiitake cuits", kcal: 56, category: "Légumes" },
  { id: "ing_442", name: "Champignons portobello", kcal: 22, category: "Légumes" },
  { id: "ing_443", name: "Champignons en boîte", kcal: 20, category: "Légumes" },
  { id: "ing_444", name: "Petits pois cuits", kcal: 84, category: "Légumes" },
  { id: "ing_445", name: "Petits pois surgelés", kcal: 68, category: "Légumes" },
  { id: "ing_446", name: "Haricots verts crus", kcal: 31, category: "Légumes" },
  { id: "ing_447", name: "Haricots verts cuits", kcal: 35, category: "Légumes" },
  { id: "ing_448", name: "Haricots verts surgelés", kcal: 30, category: "Légumes" },
  { id: "ing_449", name: "Aubergine crue", kcal: 25, category: "Légumes" },
  { id: "ing_450", name: "Aubergine cuite", kcal: 35, category: "Légumes" },
  { id: "ing_451", name: "Céleri branche cru", kcal: 16, category: "Légumes" },
  { id: "ing_452", name: "Céleri-rave cru", kcal: 42, category: "Légumes" },
  { id: "ing_453", name: "Céleri-rave cuit", kcal: 39, category: "Légumes" },
  { id: "ing_454", name: "Fenouil cru", kcal: 31, category: "Légumes" },
  { id: "ing_455", name: "Fenouil cuit", kcal: 29, category: "Légumes" },
  { id: "ing_456", name: "Betterave crue", kcal: 43, category: "Légumes" },
  { id: "ing_457", name: "Betterave cuite", kcal: 44, category: "Légumes" },
  { id: "ing_458", name: "Navet cru", kcal: 28, category: "Légumes" },
  { id: "ing_459", name: "Navet cuit", kcal: 21, category: "Légumes" },
  { id: "ing_460", name: "Radis cru", kcal: 16, category: "Légumes" },
  { id: "ing_461", name: "Asperge crue", kcal: 20, category: "Légumes" },
  { id: "ing_462", name: "Asperge cuite", kcal: 22, category: "Légumes" },
  { id: "ing_463", name: "Artichaut cuit", kcal: 53, category: "Légumes" },
  { id: "ing_464", name: "Endive crue", kcal: 17, category: "Légumes" },
  { id: "ing_465", name: "Endive cuite", kcal: 20, category: "Légumes" },
  { id: "ing_466", name: "Bette cuite", kcal: 20, category: "Légumes" },
  { id: "ing_467", name: "Cresson cru", kcal: 32, category: "Légumes" },
  { id: "ing_468", name: "Pousses de soja crues", kcal: 30, category: "Légumes" },
  { id: "ing_469", name: "Maïs doux cuit", kcal: 108, category: "Légumes" },
  { id: "ing_470", name: "Panais cru", kcal: 75, category: "Légumes" },
  { id: "ing_471", name: "Panais cuit", kcal: 71, category: "Légumes" },
  { id: "ing_472", name: "Potiron cru", kcal: 26, category: "Légumes" },
  { id: "ing_473", name: "Potiron cuit", kcal: 20, category: "Légumes" },
  { id: "ing_474", name: "Courge butternut crue", kcal: 45, category: "Légumes" },
  { id: "ing_475", name: "Courge butternut cuite", kcal: 45, category: "Légumes" },
  { id: "ing_476", name: "Épinards bébé crus", kcal: 23, category: "Légumes" },
  { id: "ing_477", name: "Pak choi cru", kcal: 13, category: "Légumes" },
  { id: "ing_478", name: "Broccolini cuit", kcal: 35, category: "Légumes" },
  { id: "ing_479", name: "Okra cuit", kcal: 33, category: "Légumes" },
  { id: "ing_480", name: "Rutabaga cuit", kcal: 39, category: "Légumes" },

  // ── FRUITS ───────────────────────────────────────────────
  { id: "ing_501", name: "Pomme", kcal: 52, category: "Fruits" },
  { id: "ing_502", name: "Banane", kcal: 89, category: "Fruits" },
  { id: "ing_503", name: "Banane plantain cuite", kcal: 122, category: "Fruits" },
  { id: "ing_504", name: "Orange", kcal: 47, category: "Fruits" },
  { id: "ing_505", name: "Clémentine", kcal: 47, category: "Fruits" },
  { id: "ing_506", name: "Mandarine", kcal: 53, category: "Fruits" },
  { id: "ing_507", name: "Pamplemousse", kcal: 42, category: "Fruits" },
  { id: "ing_508", name: "Citron", kcal: 29, category: "Fruits" },
  { id: "ing_509", name: "Citron vert", kcal: 30, category: "Fruits" },
  { id: "ing_510", name: "Fraise", kcal: 32, category: "Fruits" },
  { id: "ing_511", name: "Framboise", kcal: 52, category: "Fruits" },
  { id: "ing_512", name: "Myrtilles", kcal: 57, category: "Fruits" },
  { id: "ing_513", name: "Mûres", kcal: 43, category: "Fruits" },
  { id: "ing_514", name: "Groseilles", kcal: 44, category: "Fruits" },
  { id: "ing_515", name: "Raisin blanc", kcal: 67, category: "Fruits" },
  { id: "ing_516", name: "Raisin rouge", kcal: 70, category: "Fruits" },
  { id: "ing_517", name: "Raisins secs", kcal: 299, category: "Fruits" },
  { id: "ing_518", name: "Mangue", kcal: 60, category: "Fruits" },
  { id: "ing_519", name: "Papaye", kcal: 43, category: "Fruits" },
  { id: "ing_520", name: "Ananas frais", kcal: 50, category: "Fruits" },
  { id: "ing_521", name: "Ananas en boîte", kcal: 60, category: "Fruits" },
  { id: "ing_522", name: "Kiwi", kcal: 61, category: "Fruits" },
  { id: "ing_523", name: "Avocat", kcal: 160, category: "Fruits" },
  { id: "ing_524", name: "Poire", kcal: 57, category: "Fruits" },
  { id: "ing_525", name: "Pêche", kcal: 39, category: "Fruits" },
  { id: "ing_526", name: "Nectarine", kcal: 44, category: "Fruits" },
  { id: "ing_527", name: "Abricot frais", kcal: 48, category: "Fruits" },
  { id: "ing_528", name: "Abricot sec", kcal: 241, category: "Fruits" },
  { id: "ing_529", name: "Prune", kcal: 46, category: "Fruits" },
  { id: "ing_530", name: "Pruneau sec", kcal: 240, category: "Fruits" },
  { id: "ing_531", name: "Cerise", kcal: 63, category: "Fruits" },
  { id: "ing_532", name: "Pastèque", kcal: 30, category: "Fruits" },
  { id: "ing_533", name: "Melon", kcal: 34, category: "Fruits" },
  { id: "ing_534", name: "Figue fraîche", kcal: 74, category: "Fruits" },
  { id: "ing_535", name: "Figue sèche", kcal: 249, category: "Fruits" },
  { id: "ing_536", name: "Datte", kcal: 282, category: "Fruits" },
  { id: "ing_537", name: "Grenade", kcal: 83, category: "Fruits" },
  { id: "ing_538", name: "Litchi", kcal: 66, category: "Fruits" },
  { id: "ing_539", name: "Fruit de la passion", kcal: 97, category: "Fruits" },
  { id: "ing_540", name: "Noix de coco fraîche", kcal: 354, category: "Fruits" },

  // ── PRODUITS LAITIERS ────────────────────────────────────
  { id: "ing_601", name: "Lait entier", kcal: 61, category: "Produits Laitiers" },
  { id: "ing_602", name: "Lait demi-écrémé", kcal: 46, category: "Produits Laitiers" },
  { id: "ing_603", name: "Lait écrémé", kcal: 33, category: "Produits Laitiers" },
  { id: "ing_604", name: "Yaourt nature entier", kcal: 61, category: "Produits Laitiers" },
  { id: "ing_605", name: "Yaourt nature 0%", kcal: 45, category: "Produits Laitiers" },
  { id: "ing_606", name: "Yaourt grec entier", kcal: 97, category: "Produits Laitiers" },
  { id: "ing_607", name: "Yaourt grec 0%", kcal: 57, category: "Produits Laitiers" },
  { id: "ing_608", name: "Fromage blanc 0%", kcal: 44, category: "Produits Laitiers" },
  { id: "ing_609", name: "Fromage blanc 3%", kcal: 67, category: "Produits Laitiers" },
  { id: "ing_610", name: "Skyr nature", kcal: 63, category: "Produits Laitiers" },
  { id: "ing_611", name: "Emmental râpé", kcal: 380, category: "Produits Laitiers" },
  { id: "ing_612", name: "Emmental en tranche", kcal: 370, category: "Produits Laitiers" },
  { id: "ing_613", name: "Comté", kcal: 407, category: "Produits Laitiers" },
  { id: "ing_614", name: "Gruyère", kcal: 396, category: "Produits Laitiers" },
  { id: "ing_615", name: "Parmesan", kcal: 431, category: "Produits Laitiers" },
  { id: "ing_616", name: "Mozzarella", kcal: 280, category: "Produits Laitiers" },
  { id: "ing_617", name: "Mozzarella di bufala", kcal: 260, category: "Produits Laitiers" },
  { id: "ing_618", name: "Feta", kcal: 264, category: "Produits Laitiers" },
  { id: "ing_619", name: "Chèvre frais", kcal: 230, category: "Produits Laitiers" },
  { id: "ing_620", name: "Brie", kcal: 334, category: "Produits Laitiers" },
  { id: "ing_621", name: "Camembert", kcal: 300, category: "Produits Laitiers" },
  { id: "ing_622", name: "Roquefort", kcal: 369, category: "Produits Laitiers" },
  { id: "ing_623", name: "Raclette", kcal: 367, category: "Produits Laitiers" },
  { id: "ing_624", name: "Reblochon", kcal: 334, category: "Produits Laitiers" },
  { id: "ing_625", name: "Philadelphia / cream cheese", kcal: 342, category: "Produits Laitiers" },
  { id: "ing_626", name: "Ricotta", kcal: 174, category: "Produits Laitiers" },
  { id: "ing_627", name: "Mascarpone", kcal: 429, category: "Produits Laitiers" },
  { id: "ing_628", name: "Crème fraîche épaisse 30%", kcal: 292, category: "Produits Laitiers" },
  { id: "ing_629", name: "Crème fraîche légère 15%", kcal: 162, category: "Produits Laitiers" },
  { id: "ing_630", name: "Crème liquide entière", kcal: 335, category: "Produits Laitiers" },
  { id: "ing_631", name: "Crème liquide légère", kcal: 198, category: "Produits Laitiers" },
  { id: "ing_632", name: "Beurre", kcal: 717, category: "Produits Laitiers" },
  { id: "ing_633", name: "Beurre demi-sel", kcal: 717, category: "Produits Laitiers" },
  { id: "ing_634", name: "Beurre allégé", kcal: 400, category: "Produits Laitiers" },

  // ── LÉGUMINEUSES ─────────────────────────────────────────
  { id: "ing_701", name: "Lentilles vertes cuites", kcal: 116, category: "Légumineuses" },
  { id: "ing_702", name: "Lentilles vertes crues", kcal: 353, category: "Légumineuses" },
  { id: "ing_703", name: "Lentilles corail cuites", kcal: 100, category: "Légumineuses" },
  { id: "ing_704", name: "Lentilles beluga cuites", kcal: 116, category: "Légumineuses" },
  { id: "ing_705", name: "Pois chiches cuits", kcal: 164, category: "Légumineuses" },
  { id: "ing_706", name: "Pois chiches crus", kcal: 364, category: "Légumineuses" },
  { id: "ing_707", name: "Pois chiches en boîte", kcal: 139, category: "Légumineuses" },
  { id: "ing_708", name: "Haricots rouges cuits", kcal: 127, category: "Légumineuses" },
  { id: "ing_709", name: "Haricots rouges en boîte", kcal: 100, category: "Légumineuses" },
  { id: "ing_710", name: "Haricots blancs cuits", kcal: 139, category: "Légumineuses" },
  { id: "ing_711", name: "Haricots noirs cuits", kcal: 132, category: "Légumineuses" },
  { id: "ing_712", name: "Fèves cuites", kcal: 88, category: "Légumineuses" },
  { id: "ing_713", name: "Pois cassés cuits", kcal: 118, category: "Légumineuses" },
  { id: "ing_714", name: "Edamame", kcal: 121, category: "Légumineuses" },
  { id: "ing_715", name: "Tofu nature", kcal: 76, category: "Légumineuses" },
  { id: "ing_716", name: "Tofu fumé", kcal: 110, category: "Légumineuses" },
  { id: "ing_717", name: "Tofu soyeux", kcal: 55, category: "Légumineuses" },
  { id: "ing_718", name: "Tempeh", kcal: 192, category: "Légumineuses" },
  { id: "ing_719", name: "Seitan", kcal: 143, category: "Légumineuses" },

  // ── MATIÈRES GRASSES ─────────────────────────────────────
  { id: "ing_801", name: "Huile d'olive", kcal: 884, category: "Matières Grasses" },
  { id: "ing_802", name: "Huile de tournesol", kcal: 884, category: "Matières Grasses" },
  { id: "ing_803", name: "Huile de colza", kcal: 884, category: "Matières Grasses" },
  { id: "ing_804", name: "Huile de coco", kcal: 862, category: "Matières Grasses" },
  { id: "ing_805", name: "Huile de sésame", kcal: 884, category: "Matières Grasses" },
  { id: "ing_806", name: "Huile d'arachide", kcal: 884, category: "Matières Grasses" },
  { id: "ing_807", name: "Margarine", kcal: 717, category: "Matières Grasses" },
  { id: "ing_808", name: "Ghee (beurre clarifié)", kcal: 900, category: "Matières Grasses" },
  { id: "ing_809", name: "Saindoux", kcal: 891, category: "Matières Grasses" },

  // ── SUCRES & DOUCEURS ─────────────────────────────────────
  { id: "ing_901", name: "Sucre blanc", kcal: 387, category: "Sucres & Douceurs" },
  { id: "ing_902", name: "Sucre roux / cassonade", kcal: 377, category: "Sucres & Douceurs" },
  { id: "ing_903", name: "Miel", kcal: 304, category: "Sucres & Douceurs" },
  { id: "ing_904", name: "Sirop d'érable", kcal: 260, category: "Sucres & Douceurs" },
  { id: "ing_905", name: "Sirop d'agave", kcal: 310, category: "Sucres & Douceurs" },
  { id: "ing_906", name: "Chocolat noir 70%", kcal: 598, category: "Sucres & Douceurs" },
  { id: "ing_907", name: "Chocolat noir 85%", kcal: 600, category: "Sucres & Douceurs" },
  { id: "ing_908", name: "Chocolat au lait", kcal: 535, category: "Sucres & Douceurs" },
  { id: "ing_909", name: "Chocolat blanc", kcal: 539, category: "Sucres & Douceurs" },
  { id: "ing_910", name: "Pépites de chocolat", kcal: 530, category: "Sucres & Douceurs" },
  { id: "ing_911", name: "Cacao en poudre non sucré", kcal: 228, category: "Sucres & Douceurs" },
  { id: "ing_912", name: "Confiture", kcal: 250, category: "Sucres & Douceurs" },
  { id: "ing_913", name: "Nutella", kcal: 530, category: "Sucres & Douceurs" },
  { id: "ing_914", name: "Caramel liquide", kcal: 328, category: "Sucres & Douceurs" },
  { id: "ing_915", name: "Crème de marrons", kcal: 268, category: "Sucres & Douceurs" },

  // ── NOIX & GRAINES ────────────────────────────────────────
  { id: "ing_1001", name: "Amandes", kcal: 579, category: "Noix & Graines" },
  { id: "ing_1002", name: "Amandes effilées", kcal: 579, category: "Noix & Graines" },
  { id: "ing_1003", name: "Noix", kcal: 654, category: "Noix & Graines" },
  { id: "ing_1004", name: "Noix de cajou", kcal: 553, category: "Noix & Graines" },
  { id: "ing_1005", name: "Noix de macadamia", kcal: 718, category: "Noix & Graines" },
  { id: "ing_1006", name: "Noisettes", kcal: 628, category: "Noix & Graines" },
  { id: "ing_1007", name: "Pistaches", kcal: 562, category: "Noix & Graines" },
  { id: "ing_1008", name: "Cacahuètes", kcal: 567, category: "Noix & Graines" },
  { id: "ing_1009", name: "Noix du Brésil", kcal: 656, category: "Noix & Graines" },
  { id: "ing_1010", name: "Noix de pécan", kcal: 691, category: "Noix & Graines" },
  { id: "ing_1011", name: "Graines de chia", kcal: 486, category: "Noix & Graines" },
  { id: "ing_1012", name: "Graines de lin", kcal: 534, category: "Noix & Graines" },
  { id: "ing_1013", name: "Graines de tournesol", kcal: 584, category: "Noix & Graines" },
  { id: "ing_1014", name: "Graines de courge", kcal: 446, category: "Noix & Graines" },
  { id: "ing_1015", name: "Graines de sésame", kcal: 573, category: "Noix & Graines" },
  { id: "ing_1016", name: "Graines de pavot", kcal: 525, category: "Noix & Graines" },
  { id: "ing_1017", name: "Graines de chanvre", kcal: 553, category: "Noix & Graines" },
  { id: "ing_1018", name: "Beurre de cacahuète", kcal: 588, category: "Noix & Graines" },
  { id: "ing_1019", name: "Beurre d'amande", kcal: 614, category: "Noix & Graines" },
  { id: "ing_1020", name: "Tahini (purée sésame)", kcal: 595, category: "Noix & Graines" },

  // ── BOISSONS ─────────────────────────────────────────────
  { id: "ing_1101", name: "Jus d'orange frais", kcal: 45, category: "Boissons" },
  { id: "ing_1102", name: "Jus d'orange industriel", kcal: 42, category: "Boissons" },
  { id: "ing_1103", name: "Jus de pomme", kcal: 46, category: "Boissons" },
  { id: "ing_1104", name: "Jus de raisin", kcal: 60, category: "Boissons" },
  { id: "ing_1105", name: "Jus de tomate", kcal: 17, category: "Boissons" },
  { id: "ing_1106", name: "Jus de carotte", kcal: 40, category: "Boissons" },
  { id: "ing_1107", name: "Lait végétal avoine", kcal: 45, category: "Boissons" },
  { id: "ing_1108", name: "Lait végétal amande", kcal: 24, category: "Boissons" },
  { id: "ing_1109", name: "Lait végétal soja", kcal: 54, category: "Boissons" },
  { id: "ing_1110", name: "Lait végétal coco", kcal: 45, category: "Boissons" },
  { id: "ing_1111", name: "Café (sans sucre)", kcal: 2, category: "Boissons" },
  { id: "ing_1112", name: "Thé (sans sucre)", kcal: 1, category: "Boissons" },
  { id: "ing_1113", name: "Coca-Cola", kcal: 42, category: "Boissons" },
  { id: "ing_1114", name: "Coca-Cola Zero", kcal: 0, category: "Boissons" },
  { id: "ing_1115", name: "Jus de citron", kcal: 22, category: "Boissons" },
  { id: "ing_1116", name: "Lait concentré sucré", kcal: 321, category: "Boissons" },

  // ── SAUCES & CONDIMENTS ───────────────────────────────────
  { id: "ing_1201", name: "Ketchup", kcal: 112, category: "Sauces & Condiments" },
  { id: "ing_1202", name: "Mayonnaise", kcal: 680, category: "Sauces & Condiments" },
  { id: "ing_1203", name: "Mayonnaise allégée", kcal: 290, category: "Sauces & Condiments" },
  { id: "ing_1204", name: "Moutarde de Dijon", kcal: 66, category: "Sauces & Condiments" },
  { id: "ing_1205", name: "Moutarde à l'ancienne", kcal: 77, category: "Sauces & Condiments" },
  { id: "ing_1206", name: "Sauce soja", kcal: 53, category: "Sauces & Condiments" },
  { id: "ing_1207", name: "Sauce soja sucrée", kcal: 100, category: "Sauces & Condiments" },
  { id: "ing_1208", name: "Sauce teriyaki", kcal: 89, category: "Sauces & Condiments" },
  { id: "ing_1209", name: "Sauce hoisin", kcal: 220, category: "Sauces & Condiments" },
  { id: "ing_1210", name: "Sauce huître", kcal: 89, category: "Sauces & Condiments" },
  { id: "ing_1211", name: "Sauce poisson (nuoc-mâm)", kcal: 35, category: "Sauces & Condiments" },
  { id: "ing_1212", name: "Sauce Worcestershire", kcal: 78, category: "Sauces & Condiments" },
  { id: "ing_1213", name: "Sauce Tabasco", kcal: 12, category: "Sauces & Condiments" },
  { id: "ing_1214", name: "Sauce sriracha", kcal: 93, category: "Sauces & Condiments" },
  { id: "ing_1215", name: "Harissa", kcal: 60, category: "Sauces & Condiments" },
  { id: "ing_1216", name: "Sauce barbecue", kcal: 172, category: "Sauces & Condiments" },
  { id: "ing_1217", name: "Sauce burger", kcal: 380, category: "Sauces & Condiments" },
  { id: "ing_1218", name: "Sauce Caesar", kcal: 362, category: "Sauces & Condiments" },
  { id: "ing_1219", name: "Sauce ranch", kcal: 321, category: "Sauces & Condiments" },
  { id: "ing_1220", name: "Vinaigrette classique", kcal: 460, category: "Sauces & Condiments" },
  { id: "ing_1221", name: "Vinaigrette allégée", kcal: 110, category: "Sauces & Condiments" },
  { id: "ing_1222", name: "Vinaigre balsamique", kcal: 88, category: "Sauces & Condiments" },
  { id: "ing_1223", name: "Vinaigre de cidre", kcal: 21, category: "Sauces & Condiments" },
  { id: "ing_1224", name: "Vinaigre blanc", kcal: 18, category: "Sauces & Condiments" },
  { id: "ing_1225", name: "Coulis de tomate", kcal: 30, category: "Sauces & Condiments" },
  { id: "ing_1226", name: "Sauce tomate cuisinée", kcal: 50, category: "Sauces & Condiments" },
  { id: "ing_1227", name: "Concentré de tomate", kcal: 82, category: "Sauces & Condiments" },
  { id: "ing_1228", name: "Sauce bolognaise", kcal: 115, category: "Sauces & Condiments" },
  { id: "ing_1229", name: "Sauce béchamel", kcal: 120, category: "Sauces & Condiments" },
  { id: "ing_1230", name: "Sauce carbonara", kcal: 230, category: "Sauces & Condiments" },
  { id: "ing_1231", name: "Sauce pesto vert", kcal: 460, category: "Sauces & Condiments" },
  { id: "ing_1232", name: "Sauce pesto rouge", kcal: 370, category: "Sauces & Condiments" },
  { id: "ing_1233", name: "Sauce curry", kcal: 120, category: "Sauces & Condiments" },
  { id: "ing_1234", name: "Crème de coco", kcal: 330, category: "Sauces & Condiments" },
  { id: "ing_1235", name: "Lait de coco", kcal: 197, category: "Sauces & Condiments" },
  { id: "ing_1236", name: "Sauce tzatziki", kcal: 75, category: "Sauces & Condiments" },
  { id: "ing_1237", name: "Houmous", kcal: 177, category: "Sauces & Condiments" },
  { id: "ing_1238", name: "Guacamole", kcal: 155, category: "Sauces & Condiments" },
  { id: "ing_1239", name: "Tapenade noire", kcal: 312, category: "Sauces & Condiments" },
  { id: "ing_1240", name: "Sauce fromagère", kcal: 185, category: "Sauces & Condiments" },
  { id: "ing_1241", name: "Sauce au poivre", kcal: 170, category: "Sauces & Condiments" },
  { id: "ing_1242", name: "Sauce à la crème", kcal: 200, category: "Sauces & Condiments" },
  { id: "ing_1243", name: "Sauce bourguignonne", kcal: 90, category: "Sauces & Condiments" },
  { id: "ing_1244", name: "Sauce hollandaise", kcal: 360, category: "Sauces & Condiments" },
  { id: "ing_1245", name: "Sauce beurre blanc", kcal: 420, category: "Sauces & Condiments" },
  { id: "ing_1246", name: "Aïoli", kcal: 700, category: "Sauces & Condiments" },
  { id: "ing_1247", name: "Rouille", kcal: 380, category: "Sauces & Condiments" },
  { id: "ing_1248", name: "Sauce aigre-douce", kcal: 110, category: "Sauces & Condiments" },
  { id: "ing_1249", name: "Sauce satay (cacahuète)", kcal: 310, category: "Sauces & Condiments" },
  { id: "ing_1250", name: "Sauce tahini / sésame", kcal: 300, category: "Sauces & Condiments" },

  // ── ÉPICES & HERBES ───────────────────────────────────────
  { id: "ing_1301", name: "Sel", kcal: 0, category: "Épices & Herbes" },
  { id: "ing_1302", name: "Poivre noir", kcal: 251, category: "Épices & Herbes" },
  { id: "ing_1303", name: "Paprika", kcal: 282, category: "Épices & Herbes" },
  { id: "ing_1304", name: "Cumin en poudre", kcal: 375, category: "Épices & Herbes" },
  { id: "ing_1305", name: "Curcuma", kcal: 354, category: "Épices & Herbes" },
  { id: "ing_1306", name: "Curry en poudre", kcal: 325, category: "Épices & Herbes" },
  { id: "ing_1307", name: "Cannelle", kcal: 247, category: "Épices & Herbes" },
  { id: "ing_1308", name: "Gingembre en poudre", kcal: 335, category: "Épices & Herbes" },
  { id: "ing_1309", name: "Gingembre frais", kcal: 80, category: "Épices & Herbes" },
  { id: "ing_1310", name: "Coriandre en poudre", kcal: 298, category: "Épices & Herbes" },
  { id: "ing_1311", name: "Coriandre fraîche", kcal: 23, category: "Épices & Herbes" },
  { id: "ing_1312", name: "Persil frais", kcal: 36, category: "Épices & Herbes" },
  { id: "ing_1313", name: "Basilic frais", kcal: 23, category: "Épices & Herbes" },
  { id: "ing_1314", name: "Thym", kcal: 101, category: "Épices & Herbes" },
  { id: "ing_1315", name: "Romarin", kcal: 131, category: "Épices & Herbes" },
  { id: "ing_1316", name: "Origan", kcal: 265, category: "Épices & Herbes" },
  { id: "ing_1317", name: "Herbes de Provence", kcal: 259, category: "Épices & Herbes" },
  { id: "ing_1318", name: "Piment de Cayenne", kcal: 318, category: "Épices & Herbes" },
  { id: "ing_1319", name: "Piment d'Espelette", kcal: 265, category: "Épices & Herbes" },
  { id: "ing_1320", name: "Levure de bière", kcal: 283, category: "Épices & Herbes" },
  { id: "ing_1321", name: "Levure chimique", kcal: 53, category: "Épices & Herbes" },
  { id: "ing_1322", name: "Bicarbonate de soude", kcal: 0, category: "Épices & Herbes" },

  // ── PLATS PRÉPARÉS & FAST-FOOD ────────────────────────────
  { id: "ing_1401", name: "Pizza margherita", kcal: 250, category: "Plats préparés" },
  { id: "ing_1402", name: "Pizza 4 fromages", kcal: 280, category: "Plats préparés" },
  { id: "ing_1403", name: "Burger maison", kcal: 295, category: "Plats préparés" },
  { id: "ing_1404", name: "Burger McDonald's (Big Mac)", kcal: 257, category: "Plats préparés" },
  { id: "ing_1405", name: "Nuggets de poulet", kcal: 246, category: "Plats préparés" },
  { id: "ing_1406", name: "Kebab viande", kcal: 230, category: "Plats préparés" },
  { id: "ing_1407", name: "Quiche lorraine", kcal: 270, category: "Plats préparés" },
  { id: "ing_1408", name: "Lasagnes bolognaise", kcal: 130, category: "Plats préparés" },
  { id: "ing_1409", name: "Gratin dauphinois", kcal: 175, category: "Plats préparés" },
  { id: "ing_1410", name: "Soupe de légumes", kcal: 40, category: "Plats préparés" },
  { id: "ing_1411", name: "Soupe miso", kcal: 40, category: "Plats préparés" },
  { id: "ing_1412", name: "Ramen", kcal: 140, category: "Plats préparés" },
  { id: "ing_1413", name: "Sushi (riz + poisson)", kcal: 150, category: "Plats préparés" },
  { id: "ing_1414", name: "Crêpe nature", kcal: 200, category: "Plats préparés" },
  { id: "ing_1415", name: "Galette de sarrasin", kcal: 185, category: "Plats préparés" },
  { id: "ing_1416", name: "Pancake nature", kcal: 227, category: "Plats préparés" },
  { id: "ing_1417", name: "Wrap thon/crudités", kcal: 185, category: "Plats préparés" },
  { id: "ing_1418", name: "Sandwich jambon-beurre", kcal: 230, category: "Plats préparés" },
  { id: "ing_1419", name: "Salade César", kcal: 150, category: "Plats préparés" },
  { id: "ing_1420", name: "Taboulé", kcal: 142, category: "Plats préparés" },

  // ── DESSERTS & PÂTISSERIES ────────────────────────────────
  { id: "ing_1501", name: "Gâteau au chocolat", kcal: 380, category: "Desserts & Pâtisseries" },
  { id: "ing_1502", name: "Brownie chocolat", kcal: 415, category: "Desserts & Pâtisseries" },
  { id: "ing_1503", name: "Cookie chocolat", kcal: 488, category: "Desserts & Pâtisseries" },
  { id: "ing_1504", name: "Madeleine", kcal: 413, category: "Desserts & Pâtisseries" },
  { id: "ing_1505", name: "Croissant", kcal: 406, category: "Desserts & Pâtisseries" },
  { id: "ing_1506", name: "Pain au chocolat", kcal: 393, category: "Desserts & Pâtisseries" },
  { id: "ing_1507", name: "Éclair au chocolat", kcal: 310, category: "Desserts & Pâtisseries" },
  { id: "ing_1508", name: "Tarte aux pommes", kcal: 230, category: "Desserts & Pâtisseries" },
  { id: "ing_1509", name: "Cheesecake", kcal: 321, category: "Desserts & Pâtisseries" },
  { id: "ing_1510", name: "Tiramisu", kcal: 283, category: "Desserts & Pâtisseries" },
  { id: "ing_1511", name: "Crème brûlée", kcal: 230, category: "Desserts & Pâtisseries" },
  { id: "ing_1512", name: "Mousse au chocolat", kcal: 268, category: "Desserts & Pâtisseries" },
  { id: "ing_1513", name: "Glace vanille", kcal: 207, category: "Desserts & Pâtisseries" },
  { id: "ing_1514", name: "Glace chocolat", kcal: 216, category: "Desserts & Pâtisseries" },
  { id: "ing_1515", name: "Sorbet fruits rouges", kcal: 109, category: "Desserts & Pâtisseries" },
  { id: "ing_1516", name: "Compote de pommes sans sucre", kcal: 44, category: "Desserts & Pâtisseries" },
  { id: "ing_1517", name: "Riz au lait", kcal: 115, category: "Desserts & Pâtisseries" },
  { id: "ing_1518", name: "Flan nature", kcal: 120, category: "Desserts & Pâtisseries" },
  { id: "ing_1519", name: "Crêpe sucrée (Nutella)", kcal: 290, category: "Desserts & Pâtisseries" },
  { id: "ing_1520", name: "Gaufre nature", kcal: 291, category: "Desserts & Pâtisseries" },
];

const INGREDIENT_CATEGORIES = [
  "Céréales & Féculents",
  "Viandes",
  "Poissons & Fruits de mer",
  "Œufs",
  "Légumes",
  "Fruits",
  "Produits Laitiers",
  "Légumineuses",
  "Matières Grasses",
  "Sucres & Douceurs",
  "Noix & Graines",
  "Boissons",
  "Sauces & Condiments",
  "Épices & Herbes",
  "Plats préparés",
  "Desserts & Pâtisseries"
];
