// ============================================================
//  RECETTES PROPOSÉES
// ============================================================

const SUGGESTED_RECIPES = [
  {
    id: "rec_001",
    name: "Poulet rôti aux légumes",
    category: "Plat principal",
    servings: 2,
    prepTime: "15 min",
    cookTime: "40 min",
    kcalPerServing: 380,
    image: null,
    ingredients: [
      { name: "Poulet blanc cuit", quantity: 200, unit: "g" },
      { name: "Patate douce cuite", quantity: 150, unit: "g" },
      { name: "Brocoli cuit", quantity: 100, unit: "g" },
      { name: "Huile d'olive", quantity: 15, unit: "g" },
      { name: "Ail", quantity: 5, unit: "g" },
    ],
    steps: [
      "Préchauffer le four à 200°C.",
      "Couper le poulet et les légumes en morceaux.",
      "Mélanger avec l'huile d'olive et l'ail écrasé.",
      "Enfourner 40 min en retournant à mi-cuisson.",
    ],
    tags: ["protéiné", "équilibré", "sans gluten"],
    rating: 0,
  },
  {
    id: "rec_002",
    name: "Bowl de quinoa au saumon",
    category: "Plat principal",
    servings: 2,
    prepTime: "10 min",
    cookTime: "20 min",
    kcalPerServing: 430,
    image: null,
    ingredients: [
      { name: "Quinoa cuit", quantity: 150, unit: "g" },
      { name: "Saumon cuit", quantity: 120, unit: "g" },
      { name: "Avocat", quantity: 80, unit: "g" },
      { name: "Épinards", quantity: 50, unit: "g" },
      { name: "Sauce soja", quantity: 10, unit: "g" },
    ],
    steps: [
      "Cuire le quinoa selon les instructions.",
      "Faire cuire le saumon à la poêle 4 min de chaque côté.",
      "Assembler le bowl : quinoa, épinards, saumon émietté, avocat.",
      "Arroser de sauce soja.",
    ],
    tags: ["omega-3", "protéiné", "sans gluten"],
    rating: 0,
  },
  {
    id: "rec_003",
    name: "Omelette aux champignons",
    category: "Petit-déjeuner",
    servings: 1,
    prepTime: "5 min",
    cookTime: "8 min",
    kcalPerServing: 290,
    image: null,
    ingredients: [
      { name: "Œuf entier", quantity: 150, unit: "g" },
      { name: "Champignons", quantity: 80, unit: "g" },
      { name: "Emmental râpé", quantity: 20, unit: "g" },
      { name: "Beurre", quantity: 10, unit: "g" },
    ],
    steps: [
      "Battre les œufs avec sel et poivre.",
      "Faire revenir les champignons dans le beurre.",
      "Verser les œufs et laisser cuire à feu doux.",
      "Ajouter le fromage, plier et servir.",
    ],
    tags: ["rapide", "végétarien", "petit-déj"],
    rating: 0,
  },
  {
    id: "rec_004",
    name: "Salade grecque",
    category: "Entrée",
    servings: 2,
    prepTime: "10 min",
    cookTime: "0 min",
    kcalPerServing: 210,
    image: null,
    ingredients: [
      { name: "Tomate", quantity: 200, unit: "g" },
      { name: "Concombre", quantity: 150, unit: "g" },
      { name: "Feta", quantity: 80, unit: "g" },
      { name: "Oignon", quantity: 30, unit: "g" },
      { name: "Huile d'olive", quantity: 20, unit: "g" },
      { name: "Vinaigre balsamique", quantity: 10, unit: "g" },
    ],
    steps: [
      "Couper tomates, concombre et oignon en morceaux.",
      "Émietter la feta.",
      "Mélanger avec l'huile d'olive et le vinaigre.",
      "Assaisonner et servir frais.",
    ],
    tags: ["végétarien", "frais", "sans gluten", "rapide"],
    rating: 0,
  },
  {
    id: "rec_005",
    name: "Porridge banane-cannelle",
    category: "Petit-déjeuner",
    servings: 1,
    prepTime: "2 min",
    cookTime: "5 min",
    kcalPerServing: 310,
    image: null,
    ingredients: [
      { name: "Flocons d'avoine", quantity: 60, unit: "g" },
      { name: "Lait demi-écrémé", quantity: 200, unit: "g" },
      { name: "Banane", quantity: 80, unit: "g" },
      { name: "Miel", quantity: 10, unit: "g" },
    ],
    steps: [
      "Mélanger les flocons d'avoine avec le lait dans une casserole.",
      "Cuire à feu moyen 5 min en remuant.",
      "Servir avec la banane en rondelles et le miel.",
    ],
    tags: ["vegan", "petit-déj", "fibres"],
    rating: 0,
  },
  {
    id: "rec_006",
    name: "Curry de pois chiches",
    category: "Plat principal",
    servings: 2,
    prepTime: "10 min",
    cookTime: "25 min",
    kcalPerServing: 350,
    image: null,
    ingredients: [
      { name: "Pois chiches cuits", quantity: 200, unit: "g" },
      { name: "Coulis de tomate", quantity: 150, unit: "g" },
      { name: "Crème de coco", quantity: 60, unit: "g" },
      { name: "Oignon", quantity: 80, unit: "g" },
      { name: "Ail", quantity: 10, unit: "g" },
      { name: "Huile de coco", quantity: 15, unit: "g" },
    ],
    steps: [
      "Faire revenir l'oignon et l'ail dans l'huile de coco.",
      "Ajouter les épices (curry, cumin, curcuma).",
      "Incorporer les pois chiches, le coulis et la crème de coco.",
      "Laisser mijoter 20 min. Servir avec du riz.",
    ],
    tags: ["vegan", "sans gluten", "épicé"],
    rating: 0,
  },
  {
    id: "rec_007",
    name: "Wraps au thon",
    category: "Déjeuner",
    servings: 2,
    prepTime: "10 min",
    cookTime: "0 min",
    kcalPerServing: 320,
    image: null,
    ingredients: [
      { name: "Pain blanc", quantity: 80, unit: "g" },
      { name: "Thon en boîte (eau)", quantity: 140, unit: "g" },
      { name: "Fromage blanc 0%", quantity: 80, unit: "g" },
      { name: "Tomate", quantity: 80, unit: "g" },
      { name: "Salade verte", quantity: 40, unit: "g" },
      { name: "Moutarde", quantity: 10, unit: "g" },
    ],
    steps: [
      "Mélanger le thon égoutté avec le fromage blanc et la moutarde.",
      "Étaler sur les wraps.",
      "Ajouter la salade et les tomates coupées.",
      "Rouler et couper en deux.",
    ],
    tags: ["protéiné", "rapide", "léger"],
    rating: 0,
  },
  {
    id: "rec_008",
    name: "Smoothie bowl fraise-myrtille",
    category: "Petit-déjeuner",
    servings: 1,
    prepTime: "5 min",
    cookTime: "0 min",
    kcalPerServing: 220,
    image: null,
    ingredients: [
      { name: "Fraise", quantity: 100, unit: "g" },
      { name: "Myrtilles", quantity: 80, unit: "g" },
      { name: "Banane", quantity: 60, unit: "g" },
      { name: "Yaourt nature", quantity: 100, unit: "g" },
      { name: "Graines de chia", quantity: 10, unit: "g" },
    ],
    steps: [
      "Mixer les fruits avec le yaourt jusqu'à obtenir une texture épaisse.",
      "Verser dans un bol.",
      "Garnir de graines de chia et de quelques fruits frais.",
    ],
    tags: ["vegan", "antioxydant", "petit-déj", "frais"],
    rating: 0,
  },
];
